services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    build: requirements/mariadb/
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - "mariadb:/var/lib/mysql"
    expose:
      - 3306
  nginx:
    container_name: nginx
    build: requirements/nginx/
    networks:
      - inception
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - "wordpress:/var/www/wordpress"
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    hostname: wordpress
    build: requirements/wordpress/
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - "wordpress:/var/www/wordpress"
    ports:
      - "9000:9000"
networks:
  inception:
    driver: bridge
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/franmart/data/mariadb/"
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/franmart/data/wordpress/"
