services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    build: requirements/mariadb/
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - "mariadb:/var/lib/mysql"
    expose:
      - 3306
networks:
  inception:
    driver: bridge
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/franmart/data/mariadb/"
